-- MySQL Script generated by MySQL Workbench
-- Tue Jul 20 14:19:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema firstdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema firstdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `firstdb` DEFAULT CHARACTER SET utf8 ;
USE `firstdb` ;

-- -----------------------------------------------------
-- Table `firstdb`.`Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `firstdb`.`Funcionário` (
  `idfuncionário` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`idfuncionário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `firstdb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `firstdb`.`produto` (
  `id_produto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT(2) NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `firstdb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `firstdb`.`venda` (
  `idvenda` INT NOT NULL,
  `data` DATE NOT NULL,
  `fk_funcionário` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  PRIMARY KEY (`idvenda`, `fk_produto`),
  INDEX `fk_venda_Funcionário_idx` (`fk_funcionário` ASC) VISIBLE,
  INDEX `fk_venda_produto1_idx` (`fk_produto` ASC) VISIBLE,
  CONSTRAINT `fk_venda_Funcionário`
    FOREIGN KEY (`fk_funcionário`)
    REFERENCES `firstdb`.`Funcionário` (`idfuncionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto1`
    FOREIGN KEY (`fk_produto`)
    REFERENCES `firstdb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
